print("---------------------- Media Aritimetica--------------------------")
n1 = float(input("Digite a primeira nota do aluno: "))
n2 = float(input("Digite a segunda nota do aluno: "))
print("A média das notas {} e {} é {}.\n".format(n1, n2, ((n1+n2)/2)))
print("----------------------- Conversor de Medidas -------------------------")
medida = float(input("Digite a medida em metros: "))
print("A medida de {}m corresponde a\n{} km\n{}hm\n{}dam\n{}dm\n{}cm\n{}mm\n".format(medida,(medida/1000),(medida/100),(medida/10),(medida*10),(medida*100),(medida*1000)))
print("---------------------- Conversor de Moedas --------------------------")
m = float(input("Digite a quantidade de dinheiro"))
print("Com R${} você pode comprar U${}".format(m, (m/3.27)))
print("---------------------- Calculadora de Desconto --------------------------")
valor = float(input("Digite o valor do produto: "))
desconto = float(input("Digite a porcentagem do desconto: "))
print("O valor do produto é {}, com desconto o produto custa {}".format(valor,(valor*(1-desconto/100))))
print("--------------------- Aluguel de Carros ---------------------------")
d = int(input("Quantos dias alugado: "))
km = float(input("Quantidade de quilometros rodados: "))
print("O total a pagar é de R${}".format((60*d)+(km*0.15)))

