print('Hello World')
nome = input('Digite seu nome \n')
print('Olá ' + nome + '! Prazer em te conhecer!\n')
print('-------------Digite seu aniversário----------------')
dia = input('Dia:')
mes= input('Mes:')
ano = input('Ano:')
print('Você nasceu no dia '+ dia + ' de ' + mes + ' de ' +ano + '. Correto?\n')
print('-----------Soma simples:------------------')
n1 = int(input('Número 1: '))
n2 = int(input('Número 2: '))
print('A soma é: ', n1 + n2)
print('-----------Tipos de dados------------------')
var = input('Digite algo: \n')
print('Tipo de dado: {}\nTipo númerico: {} \nTipo alfa: {}\nTipo alfanúmerico: {}'.format(type(var) , var.isnumeric(), var.isalpha(), var.isalnum()))
print('---------------Antecessor e sucessor-----------------')
n = int(input('Digite um número: '))
print('O número escolhido foi: {} \nseu antecessor é: {}\nseu sucessor é: {}'.format(n, (n-1),(n+1)))
print('--------------------- Operações -----------------------')
n3 = int(input('Digite um número: '))
print('Dobro: {}\nTriplo: {}\nRaiz quadrada: {}'.format((n3*2), (n3*3), (n3**0.5)))
